### ISSUE TITLE
imap get message not working

### ISSUE THREAD

**Issue by renovoto** [SSilence/php-imap-client#36] opened 2016-05-25 09:26 UTC
Hi I tried $imap->getMessage($id, $withbody = true);
but I am getting the following output Array ( [to] => [from] => <> [date] => [subject] => [uid] => [unread] => [answered] => [deleted] => [body] => [html] => ) what am I doing wrong over here. please help

**Comment by renovoto** [comment] 2016-05-26 08:43
Hi, I have fixed the issue my self in imap.php on formatmessage function i added the following line 'msgno'	=> $header->Msgno in email array

**Comment by xXXIMMATTHEWXXx** [comment] 2016-12-02 20:51
No clue if you are still active on github, but if you are and the issue is fixed. Please close the issue :)

**Closed** 2016-12-06 10:29 UTC
