### ISSUE TITLE
Many notices and warnings

### ISSUE THREAD

**Issue by qualityplatforms** [SSilence/php-imap-client#81] opened 2017-01-07 16:46 UTC
### Feature request or bug
Bug

### If a bug, what did you expect to happen?
No notices and warnings

### If a bug, what happened?
When loading attachments i'll get many warnings and notices

### If a bug, list steps to reproduce bugs.
https://pastebin.com/heH1erzj <-- Error 

`			require_once "external/PHP/ImapClient/ImapClientException.php";
			require_once "external/PHP/ImapClient/ImapConnect.php";
			require_once "external/PHP/ImapClient/ImapClient.php";
			
			$mailbox = 'imap_server';
			$username = 'support@domain';
			$password = 'password';
			$encryption = \SSilence\ImapClient\ImapClient::ENCRYPT_SSL; // or ImapClient::ENCRYPT_SSL or ImapClient::ENCRYPT_TLS or null
			$imap = new \SSilence\ImapClient\ImapClient($mailbox, $username, $password, $encryption);
			
			if($imap->isConnected()===false) {
			    die($imap->getError());
			}
			
			$imap->selectFolder("Inbox");
			$emails = $imap->getMessages();
			return $emails;`

### If a bug, did you do these steps?
[DONE] Download and use the lastest stable version
[DONE] See if the issue has already been reported
[] Debug

**Comment by xXXIMMATTHEWXXx** [comment] 2017-01-07 18:17
Thank you for reporting this! Do you mind showing your current code?

**Comment by qualityplatforms** [comment] 2017-01-07 18:28
No problem. 

## controller
```
public function overview($offset = 0)
{
	$model = new \plugin\mail\model;
	
	$maillist	= $model->getMail();
	
	$total = count( $maillist ); //total items in array    
	$limit = 20; //per page    
	$totalPages = ceil( $total/ $limit ); //calculate total pages
	$page = max($page, 1); //get 1 page when $_GET['page'] <= 0
	$page = min($page, $totalPages); //get last page when $_GET['page'] > $totalPages
	$offset = ($page - 1) * $limit;
	if( $offset < 0 ) $offset = 0;
	
	$maillist	= array_slice( $maillist, $offset, $limit ); 
	$viewer		= file_get_contents('plugin/mail/viewer/mail_list.php');
	
	$mails = "";
	
	
	foreach($maillist as $key => $value)
	{
		if(empty($value["attachments"]))
		{
			$attachment = "";
		}
		else
		{
			$attachment = "<i class='fa fa-paperclip'></i>";
		}
		
		$mails .= "<tr class='unread'>
		<td class='inbox-small-cells'>
		<input type='checkbox' class='mail-checkbox'>
		</td>
		<td class='inbox-small-cells'><i class='fa fa-star'></i></td>
		<td class='view-message  dont-show'><a href='/mail/bekijk/".$value['id']."'>". $value["from"] ."</a></td>
		<td class='view-message '><a href='/mail/bekijk/".$value['id']."'>". $value["subject"] ."</a></td>
		<td class='view-message  inbox-small-cells'>$attachment</i></td>
		<td class='view-message  text-right'><a href='/mail/bekijk/".$value['id']."'>". $value["date"] ."</a></td>
		</tr>";
	}
	
	$viewer = str_replace('[MESSAGES_LIST]', $mails, $viewer);
	return $viewer;
}
```

## model
```
function getMail()
{
	require_once "external/PHP/ImapClient/ImapClientException.php";
	require_once "external/PHP/ImapClient/ImapConnect.php";
	require_once "external/PHP/ImapClient/ImapClient.php";
	
	$mailbox = 'imap.domain.com';
	$username = 'info@domain.com';
	$password = 'password';
	$encryption = \SSilence\ImapClient\ImapClient::ENCRYPT_SSL; // or ImapClient::ENCRYPT_SSL or ImapClient::ENCRYPT_TLS or null
	$imap = new \SSilence\ImapClient\ImapClient($mailbox, $username, $password, $encryption);
	
	if($imap->isConnected()===false) {
	    die($imap->getError());
	}
	
	$imap->selectFolder("Inbox");
	$emails = $imap->getMessages();
	return $emails;
}
```

**Comment by qualityplatforms** [comment] 2017-01-07 18:47
Some strange var_dumps:

## With no attachments
```
  ["attachments"]=>
  array(7) {
    [0]=>
    array(4) {
      ["name"]=>
      string(1) "u"
      ["size"]=>
      string(1) "u"
      ["disposition"]=>
      string(1) "u"
      ["reference"]=>
      string(1) "u"
    }
    [1]=>
    array(4) {
      ["name"]=>
      string(0) ""
      ["size"]=>
      string(0) ""
      ["disposition"]=>
      string(0) ""
      ["reference"]=>
      string(0) ""
    }
    [2]=>
    array(4) {
      ["name"]=>
      string(0) ""
      ["size"]=>
      NULL
      ["disposition"]=>
      NULL
      ["reference"]=>
      NULL
    }
    [3]=>
    array(4) {
      ["name"]=>
      string(0) ""
      ["size"]=>
      NULL
      ["disposition"]=>
      NULL
      ["reference"]=>
      NULL
    }
    [4]=>
    array(4) {
      ["name"]=>
      string(0) ""
      ["size"]=>
      string(0) ""
      ["disposition"]=>
      string(0) ""
      ["reference"]=>
      string(0) ""
    }
    [5]=>
    array(4) {
      ["name"]=>
      string(1) "a"
      ["size"]=>
      string(1) "a"
      ["disposition"]=>
      string(1) "a"
      ["reference"]=>
      string(1) "a"
    }
    [6]=>
    array(4) {
      ["name"]=>
      string(1) "P"
      ["size"]=>
      string(1) "P"
      ["disposition"]=>
      string(1) "P"
      ["reference"]=>
      string(1) "P"
    }
  }
}
```

## With an attachment
```
  ["attachments"]=>
  array(1) {
    [0]=>
    array(4) {
      ["name"]=>
      string(22) "test.txt"
      ["size"]=>
      int(2740)
      ["disposition"]=>
      string(10) "attachment"
      ["reference"]=>
      string(0) ""
    }
  }
}
```

**Comment by xXXIMMATTHEWXXx** [comment] 2017-01-07 19:02
Hmm. . . I'll look into this

**Comment by qualityplatforms** [comment] 2017-01-07 19:03
Matthew, do you need any other information?

**Comment by xXXIMMATTHEWXXx** [comment] 2017-01-07 19:03
Should be all I need, Thanks. If I need any more info ill be sure to ask

**Comment by xXXIMMATTHEWXXx** [comment] 2017-01-07 19:09
Did you install via composer or manually

**Comment by qualityplatforms** [comment] 2017-01-07 19:14
It's manually.

**Comment by xXXIMMATTHEWXXx** [comment] 2017-01-07 19:15
Thanks

**Comment by xXXIMMATTHEWXXx** [comment] 2017-01-23 15:34
Hello. This issues seems to be linked to the other issue about attachments and it is being worked on. Try everything again with the latest version

**Comment by qualityplatforms** [comment] 2017-01-23 17:02
Well. I tried to update the system.

``` 
PHP Fatal error:  Uncaught exception 'SSilence\\ImapClient\\ImapClientException' with message 'Your attachments do not have a name. This should NOT be happening' in ImapClient/ImapClient.php:911
```

**Comment by xXXIMMATTHEWXXx** [comment] 2017-01-23 17:04
Hmm. This is thrown when the attachments name is null. Let me reverse what
I did and I'll comment back so you can test again. Thanks for helping
improve this library

**Comment by qualityplatforms** [comment] 2017-01-23 17:06
I think you must ignore the attachments instead of throw an exception. Otherwise you kill the system, like it's now happening ;)

**Comment by xXXIMMATTHEWXXx** [comment] 2017-01-23 17:09
Good idea! I will be sure to fix this up later:D


On Jan 23, 2017 12:06 PM, "Mark" <notifications@github.com> wrote:

I think you must ignore the attachments instead of throw an exception.
Otherwise you kill the system, like it's now happening ;)

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/SSilence/php-imap-client/issues/81#issuecomment-274549769>,
or mute the thread

**Comment by Decksi** [comment] 2017-01-23 17:51
Same Error here:

"Your attachments do not have a name. This should NOT be happening"

Just started a connection and requested the unread Messages :(

**Comment by xXXIMMATTHEWXXx** [comment] 2017-01-23 21:40
Try with the lastest commits

**Comment by Decksi** [comment] 2017-01-23 23:02
Nope. Sorry.:

Notice (8): Undefined offset: 0 [ROOT/vendor/ssilence/php-imap-client/ImapClient/ImapClient.php, line 579]
Notice (8): Trying to get property of non-object [ROOT/vendor/ssilence/php-imap-client/ImapClient/ImapClient.php, line 579]

**Comment by xXXIMMATTHEWXXx** [comment] 2017-02-07 14:20
This should be fixed now. Try one more time

**Comment by myspulin** [comment] 2017-02-12 11:09
Hi, I did a small analysis of this issue, found a solution:

This is the call of function attachments2name($attachments)

dump of variable attachments:

array (size=7)
  'name' => string 'utf-8' (length=5)
  'partNum' => string '' (length=0)
  'enc' => null
  'size' => int 729
  'reference' => string '' (length=0)
  'disposition' => string 'attachment' (length=10)
  'type' => string 'HTML' (length=4)

result of calling foreach ($attachments as $attachment) {  }

string 'utf-8' (length=5)

As it is not an array of attachments foreach gives the first item of array, in the code is 'name' => $attachment['name'] gives the notice of Illegal string offset 'name'  of course.

Solution is to update the function like this:

protected function attachments2name($attachments) {

$names = array();

if (isset($attachments[0]['name'])) {
          foreach ($attachments as $attachment) { 
            $names[] = array(
                'name' => $attachment['name'],
                'size' => $attachment['size'],
                "disposition" => $attachment['disposition'],
                "reference" => $attachment['reference']
            );
            }
        } else {
           	$names[] = array(
                 'name' => $attachments['name'],
                 'size' => $attachments['size'],
                 "disposition" => $attachments['disposition'],
                 "reference" => $attachments['reference']
            );
        }
        
        return $names;

}

So the key is test if array is actually array of attachments or just a single item. In my case all all warnings are gone. Could you please fix this issue, thanks.

Best regards, Lukas

**Comment by xXXIMMATTHEWXXx** [comment] 2017-02-13 18:33
Updated. Github auto closed this. If the issues continues, comment back

**Comment by Jarlskov** [comment] 2017-03-25 19:59
I get the `Your attachments do not have a name. This should NOT be happening` error as well.

This is the code where I try to read the messages.

```
foreach ($imapClient->getFolders() as $folder => $trash) {
    if ($competitors->has($folder)) {
        $competitor = $competitors->get($folder);
        $imapClient->selectFolder($folder);
        if ($imapClient->countUnreadMessages()) {
            $messages = $imapClient->getMessages();
        }
    }
}
```

My issue seems to be in `ImapClient` line 1136, 1138 and 1139.
The `$attachments` array I get is an array with child arrays:
```
array:2 [
  0 => array:7 [
    "name" => "UTF-8"
    "partNum" => 1
    "enc" => 4
    "size" => 1394
    "reference" => ""
    "disposition" => "attachment"
    "type" => "PLAIN"
  ]
  1 => array:7 [
    "name" => "UTF-8"
    "partNum" => 2
    "enc" => 4
    "size" => 5631
    "reference" => ""
    "disposition" => "attachment"
    "type" => "HTML"
  ]
]
```
The issue is that when looping through the array, the code looks for the name in a child of the child arrays `if (isset($attachment[0]['name'])) {`, but `$attachment` is an array with named keys, and `$attachment[0]` doesn't exist, since the `['name']` key is in `$attachment` itself.

**Comment by xXXIMMATTHEWXXx** [comment] 2017-03-25 20:44
Okay. This is with the latest code correct?

**Comment by Jarlskov** [comment] 2017-03-26 00:18
I've run composer update today to be sure.

**Comment by xXXIMMATTHEWXXx** [comment] 2017-03-26 00:19
The issue is still there? As far as I know that error was removed. Will
check in a minute though

**Comment by Jarlskov** [comment] 2017-03-26 00:23
Yes, it's still looking for a child array in `$attachment` https://github.com/SSilence/php-imap-client/blob/master/ImapClient/ImapClient.php#L1136

**Comment by xXXIMMATTHEWXXx** [comment] 2017-03-26 00:26
Thank you. I'll look in to fixing it in just a bit

**Comment by Jarlskov** [comment] 2017-03-26 00:33
If it's just a matter of removing the 0-key lookup I can submit a PR on it tomorrow, I just don't know IMAP well enough to know if that's a good solution.

**Comment by sergey144010** [comment] 2017-03-26 07:48
Try like this
`
        if ($imapClient->countUnreadMessages()) {
            $messagesArray = $imapClient->getUnreadMessages();
        }
`

**Comment by sergey144010** [comment] 2017-03-26 07:51
next, for example
`
foreach($messagesArray as $inMessage){
    var_dump($inMessage->message->plain);
};
`

**Comment by sergey144010** [comment] 2017-03-26 07:58
or
`
foreach($messagesArray as $inMessage){
    $imapClient->saveAttachments(['dir' => "your/path/", 'incomingMessage' => $inMessage]);
};
`

**Comment by sergey144010** [comment] 2017-03-26 08:14
And please write here, this way is working or not.

**Comment by Jarlskov** [comment] 2017-03-26 09:13
`getUnreadMessages()` seems to work without blowing up. I think I can make my use case work that way, but it doesn't really solve the core issue since it's another use case.
The `saveAttachments` probably won't help me, since I really don't care about the attachments, and I don't think any of the emails have any real attachments.

**Comment by sergey144010** [comment] 2017-03-26 10:04
Try it after take pull request.

**Comment by Jarlskov** [comment] 2017-03-26 10:45
I'm not sure what you want me to do :/

**Comment by xXXIMMATTHEWXXx** [comment] 2017-03-27 11:27
We wants you to test after his latest pull request. Which I just merged

**Comment by xXXIMMATTHEWXXx** [comment] 2017-03-29 11:31
This issue seems to be fixed with our latest updates, @Jarlskov please let us know if there is still an issue or not.

**Comment by xXXIMMATTHEWXXx** [comment] 2017-04-03 12:35
Closed for inactivity. This issue has been resolved.

**Closed by xXXIMMATTHEWXXx** 2017-04-03 12:35 UTC
Labels: bug, Needs Fixing before next release, question
