### ISSUE TITLE
The method deleteMessages($ids) only marks messages for deletion and does not really delete them

### ISSUE THREAD

**Issue by balucio** [SSilence/php-imap-client#83] opened 2017-01-12 15:27 UTC
### Feature request or bug

Method deleteMessage or deleteMessages should really delete message not only mark for deletion.

### If a bug, what did you expect to happen?

When deleteMessage is called, the message should be deleted (ie.moved to trash)

### If a bug, what happened?

Message are not deleted (Tested on Zimbra)

### If a bug, list steps to reproduce bugs.

Open an imap connection and call deleteMessage($id)

### If a bug, did you do these steps?
[x] Download and use the lastest stable version
[] See if the issue has already been reported
[x] Debug

### If a feature request, what do you want to be added or changed?

In order to really delete the message after calling imap_delete function the function imap_expunge should be called see: http://php.net/manual/en/function.imap-expunge.php

**Comment by xXXIMMATTHEWXXx** [comment] 2017-01-12 15:28
Thank you for reporting this issue! It will be looked into!

**Comment by xXXIMMATTHEWXXx** [comment] 2017-01-12 15:38
https://github.com/SSilence/php-imap-client/blob/master/ImapClient/ImapClient.php#L616 seems to call expunge

**Comment by xXXIMMATTHEWXXx** [comment] 2017-01-12 17:28
Here is the current code for deleting messages:
```php
   public function deleteMessages($ids) {
        foreach ($ids as $id) {
            imap_delete($this->imap, $id, FT_UID);
        }
        /*
        if( imap_mail_move($this->imap, implode(",", $ids), $this->getTrash(), CP_UID) == false)
            return false;
        */
        return imap_expunge($this->imap);
    }
```
As you can see, first, all messages are marked for deletion via imap_delete. Under that is some currently un-stable feature. Finally the code returns a Boolean from the imap_explunge function. This issue seems to be invalid to me. Let me know or this issue will be closed tomorrow

**Comment by xXXIMMATTHEWXXx** [comment] 2017-01-13 13:08
This is marked as invalid and because the OP did not respond within another day, this will be closed. It seems to do exactly what you said it should. If this is not the case comment back and i will reopen this. Thank you for opening this and we are ready to accept an further issues by you!

**Comment by SonnyLCD** [comment] 2017-01-16 09:44
Hi

And first of all, thanks for a great job with this imap client library.

Hmmm .. I have this problem on my mail server too, `deleteMessage()` does not work, at least not on my mail server. 

We are using this imap class in a Phalcon setup against a postfix based mail server.

There is a general mixup between uid and msg_number, which comes from the PHP/IMAP library where they mix it up all the time. I am using the uid, like this in our case:

```
$imap = $this->imap;
$imap->selectFolder("Inbox");
$imap->deleteMessage($uid);
```

But nothing happens, I also tried to call `$imap->getError();` after deletion, but it doesn't return any error. 

Is the same when trying to move an email to another folder, or save a Draft.

Seems like expunge is not called, or imap_close with CL_EXPUNGE, so the delete/move or save as draft is not executed ?

**Comment by xXXIMMATTHEWXXx** [comment] 2017-01-16 20:28
Hmm. Ill look into it

**Comment by SonnyLCD** [comment] 2017-01-17 08:34
I tried removing FT_UID form this line in the deleteMessages() function:

`map_delete($this->imap, $id, FT_UID);`

to simply this:

`map_delete($this->imap, $id);`

And at least on my mail server this did the trick...

**Comment by AndyKirkMPS** [comment] 2017-01-18 23:26
The same fix by SonnyLCD worked on my Ubuntu 14, with Postfix and Courier

**Comment by GIAPB** [comment] 2017-01-18 23:54
Hello. This has been confirmed by @xXXIMMATTHEWXXx. Im the bot so ill do my job !

**Closed** 2017-01-18 23:56 UTC
Labels: bug, invalid, Needs Detail, Needs review
