### ISSUE TITLE
convertToUtf8 function

### ISSUE THREAD

**Issue by omerilk** [SSilence/php-imap-client#186] opened 2017-08-10 08:48 UTC
### Feature request or bug
bug

### If a bug, what did you expect to happen?
convertToUtf8 function is converting the strings to UTF8 charset. But it is not taking care to source charset of string.

public function convertToUtf8($str) {
        if (mb_detect_encoding($str, "UTF-8, ISO-8859-1, GBK")!="UTF-8") {
            $str = utf8_encode($str);
        }
        $str = iconv('UTF-8', 'UTF-8//IGNORE', $str);
        return $str;
    }

### If a bug, what happened?
if the source string is not ISO-8859-1, benerated strings by convertToUtf8 function are unreadable

### If a bug, list steps to reproduce bugs.
if recipient address charset is not ISO-8859-1 or UTF-8 problem can be reproduce

### If a bug, did you do these steps?
[x] Download and use the lastest stable version
[x] See if the issue has already been reported
[] Debug

### Side notes(Read then del this chunk)
related modifications as an example

   protected function toAddress($headerinfos) {
        $email = "";
        $name = "";
        if (isset($headerinfos->mailbox) && isset($headerinfos->host)) {
            $email = $headerinfos->mailbox . "@" . $headerinfos->host;
        }
        if (!empty($headerinfos->personal)) {
            $name = imap_mime_header_decode($headerinfos->personal);
            $name = $name[0]->text;
++       $charset = $name[0]->charset;
        } else {
            $name = $email;
        }
        $name = $this->convertToUtf8($name, $charset);
        return $name . " <" . $email . ">";
    }

    public function convertToUtf8($str, $charset = 'ISO-8859-1') {
        $str = iconv($charset, 'UTF-8//IGNORE', $str);
        return $str;
    }

**Comment by xXXIMMATTHEWXXx** [comment] 2017-08-10 12:59
Thank you! I will look into this

**Comment by xXXIMMATTHEWXXx** [comment] 2017-08-30 18:08
@sergey144010  if you would.....

**Comment by xXXIMMATTHEWXXx** [comment] 2017-09-28 16:36
According to this code: 
   public function convertToUtf8($str) {
        if (mb_detect_encoding($str, "UTF-8, ISO-8859-1, GBK")!="UTF-8") {
            $str = utf8_encode($str);
        }
        $str = iconv('UTF-8', 'UTF-8//IGNORE', $str);
        return $str;
    }
If, its not utf8, we encode to utf8, then decode it. Ignoring special characters, then it retuyrns the string. Could you provide the code you are using?

**Comment by reimax** [comment] 2017-10-16 10:32
```
function convert_to_utf8($str) {
	return iconv(mb_detect_encoding($str, mb_detect_order(), true), "UTF-8", $str);
}
```

in Documentation i see setEncoding() but if use, get error.

**Comment by xXXIMMATTHEWXXx** [comment] 2017-10-16 17:25
Would you please post that error?

**Comment by reimax** [comment] 2017-10-16 19:40
setEncoding() i see in archive/ImapClient.php
in ImapClient/ImapClient.php there is no such this function

http://ssilence.github.io/php-imap-client/methods.html - in documentation setEncoding()

is there a solution to the encoding problem now? some letters are defined correctly, some are not. The methods listed in this thread do not help. checked when connecting to office 365.

**Comment by brendonofficial** [comment] 2017-12-05 21:02
Perhaps this library should look at using [neitanod/forceutf8](https://github.com/neitanod/forceutf8) for UTF-8 conversion?

**Comment by xXXIMMATTHEWXXx** [comment] 2017-12-06 12:20
I will look into it. However we may need a library that does more then
UTF-8 as this may not be intended behavior.

**Comment by xXXIMMATTHEWXXx** [comment] 2018-02-13 14:12
Should be fixed as of latest commit.

**Closed by xXXIMMATTHEWXXx** 2018-02-13 14:12 UTC
Labels: enhancement

**Comment by reimax** [comment] 2020-03-30 14:07
i tested witch message in koi8-r end not work...

```
SSilence\ImapClient\IncomingMessage Object
(
    [header] => stdClass Object
        (
            [subject] => RE: ???????????? ?????????? ???????????? ?
            [from] => ?????? ???????? 
            [to] => ???? ???????? 
```
